### ISSUE TITLE
Solve the problem json versus hal+json

### ISSUE THREAD

**Issue by clemens-tolboom** [clemens-tolboom/drupal-8-rest-angularjs#3]
AFAIK we cannot post/patch in json requests.

Currently all request goes as hal+json which is far from ideal.

**Comment by nevos** [comment]
Looking at the config - it's necessary to add json only permission on REST to view the node content.
otherwise you get 406 (Not Acceptable).

**Comment by clemens-tolboom** [comment]
The problem lies in the node life cycle. We can now test edit a node on node/lifecycle (it's a little grumpy so use refresh on DELETE, POST, PATCH)

That is only possible if we fetch a node in hal+json as POST/PATCH needs node._links AFAIK to work. There are core bugs on the json data flow.

I've added #6 to mitigate this a little in the future.

**Comment by clemens-tolboom** [comment]
@nevos what config do you refer?

**Comment by clemens-tolboom** [comment]
For now I require __hal_json__ for all interaction.
